[package]
name = "walletgen"
version = "0.1.1"
authors = ["DEADBLACKCLOVER <deadblackclover@protonmail.com>"]
description = "CLI address generator for Acryl or Waves"
edition = "2018"
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/Allnero/wallet-generator"
repository = "https://github.com/Allnero/wallet-generator"
keywords = ["address", "blockchain", "acryl", "waves", "allnero"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
acryl = "0.4.1"
clap = "2.33.0"
